#
# PROJECT: GDTLancer
# MODULE: constants.py
# STATUS: [Level 2 - Implementation]
# TRUTH_LINK: TRUTH_SIMULATION-GRAPH.md §6 + TACTICAL_TODO.md TASK_3
# LOG_REF: 2026-02-21 (TASK_2)
#

"""Qualitative simulation constants (Phase 1 gut of numeric model)."""

# === World Age Cycle ===
WORLD_AGE_CYCLE = ["PROSPERITY", "DISRUPTION", "RECOVERY"]
WORLD_AGE_DURATIONS = {
    "PROSPERITY": 420,
    "DISRUPTION": 210,
    "RECOVERY": 270,
}
WORLD_AGE_CONFIGS = {
    "PROSPERITY": {},
    "DISRUPTION": {},
    "RECOVERY": {},
}

# === Colony Structure ===
COLONY_LEVELS = ["frontier", "outpost", "colony", "hub"]
COLONY_UPGRADE_TICKS_REQUIRED = 80
COLONY_DOWNGRADE_TICKS_REQUIRED = 100
COLONY_UPGRADE_REQUIRED_SECURITY = "SECURE"
COLONY_UPGRADE_REQUIRED_ECONOMY = ["RAW_ADEQUATE", "MANUFACTURED_ADEQUATE", "CURRENCY_ADEQUATE"]
COLONY_DOWNGRADE_SECURITY_TRIGGER = "LAWLESS"
COLONY_DOWNGRADE_ECONOMY_TRIGGER = ["RAW_POOR", "MANUFACTURED_POOR", "CURRENCY_POOR"]

# === Affinity Thresholds ===
ATTACK_THRESHOLD = 1.2
TRADE_THRESHOLD = 0.5
FLEE_THRESHOLD = -1.0

# === Agent Upkeep ===
AGENT_UPKEEP_CHANCE = 0.02

# === Mortal Spawn Conditions (tag-based) ===
MORTAL_GLOBAL_CAP = 20
MORTAL_SPAWN_REQUIRED_SECURITY = ["SECURE", "CONTESTED", "LAWLESS"]
MORTAL_SPAWN_BLOCKED_SECTOR_TAGS = ["DISABLED", "HOSTILE_INFESTED"]
MORTAL_SPAWN_CHANCE = 0.08
MORTAL_ROLES = ["trader", "hauler", "prospector", "explorer", "pirate"]

# === Structural Constants (caps / timeouts) ===
EVENT_BUFFER_CAP = 200
RUMOR_BUFFER_CAP = 200
RESPAWN_COOLDOWN_TICKS = 5
RESPAWN_COOLDOWN_MAX_DEBT = 200
SECTOR_DISCOVERY_CAP = 10

# === Catastrophe ===
CATASTROPHE_CHANCE_PER_TICK = 0.0005
CATASTROPHE_DISABLE_DURATION = 50

